FROM python:3.13-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirements.frontend.txt ./
RUN --mount=type=cache,target=/root/.cache/pip python -m pip install --upgrade pip && python -m pip install --default-timeout=120 --retries=10 -r requirements.frontend.txt
COPY app ./app
COPY src ./src
COPY configs ./configs
EXPOSE 8501
CMD ["python", "-m", "streamlit", "run", "app/frontend/Home.py", "--server.address", "0.0.0.0", "--server.port", "8501"]
